### ISSUE TITLE
Multiple docs versions

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/yadism#37]
### Goals
- [x] multiple versions of the docs deployed
- [x] redirect to `master`/`stable` from the base domain (or write a home page)
  - *when ready*: delete all top level files, keep only `.nojekyll`, the redirecting, and the automatically deployed subfolders
- [x] update the docs to show the correct version (below the logo)
  - instead of using the one manually update the file in the workflow with the content of `$dest_dir` (of course before building)
- [x] add the switching version widget

### Rationale
It seems useful to be able to look at the developing docs online, furthermore if there are multiple authors working on it, or if you want to present something to someone else.  
On the other hand it seems a really bad idea to replace the master documentation with some unstable version, so it is important that the main (landing) one it is the one related to the current release (or master for the time being).

**Comment by AleCandido** [comment]
Strategy for multiple goals

## `develop` docs
First choose one of the following:
1. Write a new workflow to run from `develop` branch only
2. Use the variable [`GITHUB_REF`](https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables) to separate from `master`

Than set the [`TARGET_FOLDER`](https://github.com/JamesIves/github-pages-deploy-action#optional-choices) variable in the `github-pages-deploy-action`, by:
1. choosing your favourite name for `develop` docs
2. use a [conditional github expression](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions), e.g.:
```yaml
          TARGET_FOLDER: ${{ github.ref }}
```
or
```yaml
      - name: Deploy 🚀
        if: github.ref == 'master'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          TARGET_FOLDER: ${{ github.ref }}
      - name: Deploy 🚀
        if: github.ref == 'develop'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          TARGET_FOLDER: "dontrelymeimunstable"
```
### version docs only
if using the strategy 1. try using 2. for the `master` only workflow, i.e. use `          TARGET_FOLDER: ${{ github.ref }}`
